import React from 'react';

export default function JsonLd() {
  const structuredData = [
    // 1. Organization
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      "name": "Pharmalytix AI",
      "url": "https://pharmalytix-ai.vercel.app",
      "logo": "https://pharmalytix-ai.vercel.app/brand-logo.png",
      "sameAs": [
        "https://twitter.com/pharmalytixai",
        "https://linkedin.com/company/pharmalytixai"
      ],
      "contactPoint": {
        "@type": "ContactPoint",
        "telephone": "+1-800-PHARMA-AI",
        "contactType": "customer service"
      }
    },
    // 2. WebSite
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "name": "Pharmalytix AI",
      "url": "https://pharmalytix-ai.vercel.app",
      "potentialAction": {
        "@type": "SearchAction",
        "target": "https://pharmalytix-ai.vercel.app/dashboard/inventory?q={search_term_string}",
        "query-input": "required name=search_term_string"
      }
    },
    // 3. WebPage
    {
      "@context": "https://schema.org",
      "@type": "WebPage",
      "name": "Pharmacy Dashboard - Pharmalytix AI",
      "description": "Smart pharmacy management dashboard with AI inventory forecasting and real-time sales tracking.",
      "breadcrumb": "Dashboard > Inventory > Sales"
    },
    // 4. FAQPage
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "How does AI forecasting work?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Our AI analyzes past 30 days of sales data and uses Google Gemini to predict future demand and determine safety buffers."
          }
        },
        {
          "@type": "Question",
          "name": "Is my data secure?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes, we use secure NextAuth v5, encrypted passwords, and role-based access control to protect your pharmacy data."
          }
        }
      ]
    },
    // 5. ItemList (Features)
    {
      "@context": "https://schema.org",
      "@type": "ItemList",
      "itemListElement": [
        { "@type": "ListItem", "position": 1, "name": "Inventory Management" },
        { "@type": "ListItem", "position": 2, "name": "AI Demand Forecasting" },
        { "@type": "ListItem", "position": 3, "name": "Point of Sale (POS)" },
        { "@type": "ListItem", "position": 4, "name": "Financial Reporting" }
      ]
    },
    // 6. AggregateRating
    {
      "@context": "https://schema.org",
      "@type": "Product",
      "name": "Pharmalytix AI",
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.9",
        "reviewCount": "150"
      }
    },
    // 7. HowTo
    {
      "@context": "https://schema.org",
      "@type": "HowTo",
      "name": "How to generate an Inventoy Forecast",
      "step": [
        {
          "@type": "HowToStep",
          "text": "Navigate to the AI Forecasting tab in your dashboard."
        },
        {
          "@type": "HowToStep",
          "text": "Review the suggested reorder quantities generated by Gemini AI."
        }
      ]
    },
    // 8. SiteNavigationElement
    {
      "@context": "https://schema.org",
      "@type": "SiteNavigationElement",
      "hasPart": [
        { "@type": "WebPage", "name": "Dashboard", "url": "https://pharmalytix-ai.vercel.app/dashboard" },
        { "@type": "WebPage", "name": "Inventory", "url": "https://pharmalytix-ai.vercel.app/dashboard/inventory" },
        { "@type": "WebPage", "name": "Sales", "url": "https://pharmalytix-ai.vercel.app/dashboard/sales" }
      ]
    }
  ];

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
    />
  );
}
